export const permissoes = {
    RADAR: {
        SENADO_INCLUIR: 'ROLE_RADS_INCLUIR',
        SENADO_CONSULTAR: 'ROLE_RADS_CONSULTAR',
        SENADO_ALTERAR: 'ROLE_RADS_ALTERAR',
        SENADO_EXCLUIR: 'ROLE_RADS_EXCLUIR',
        CAMARA_INCLUIR: 'ROLE_RADC_INCLUIR',
        CAMARA_CONSULTAR: 'ROLE_RADC_CONSULTAR',
        CAMARA_ALTERAR: 'ROLE_RADC_ALTERAR',
        CAMARA_EXCLUIR: 'ROLE_RADC_EXCLUIR'
    },
    PROPOSICAO: {
        CONSULTAR: 'ROLE_PROP_CONSULTAR',
        ALTERAR: 'ROLE_PROP_ALTERAR'
    },

};
